/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quizprogram;

import quizprogram.DataHandler;
import quizprogram.Question;
import quizprogram.Quiz;

/**
 *
 * @author dianebelanger
 */
public class QuizBuilder extends BaseWindow {

    private SubjectWindow subjectWindow;
    private Quiz quiz;
    private int questionNumber = 1;
    private String selectedName;
    private String subjectName;
    
    /**
     * Creates new form QuizBuilder
     */
    public QuizBuilder(String subjectName) {
        super();
        initComponents();
        this.subjectName = subjectName;
        quiz = new Quiz();
        questionTextField.setText("");
        answerTextField.setText("");
        setVisible(false);
    }

    public void setSelectedName(String name) {
        selectedName = name;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        questionLabel = new javax.swing.JLabel();
        addQuestionButton = new javax.swing.JButton();
        questionTextField = new javax.swing.JTextField();
        answerLabel = new javax.swing.JLabel();
        answerTextField = new javax.swing.JTextField();
        doneButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        questionLabel.setText("Question:");

        addQuestionButton.setText("Add Question");
        addQuestionButton.setToolTipText("");
        addQuestionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addQuestionButtonActionPerformed(evt);
            }
        });

        questionTextField.setToolTipText("");

        answerLabel.setText("Answer:");

        answerTextField.setToolTipText("");

        doneButton.setText("Done");
        doneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(questionLabel)
                    .addComponent(answerLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(answerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(questionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addQuestionButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(doneButton)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(questionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(questionLabel))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(answerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(answerLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addQuestionButton)
                    .addComponent(doneButton))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addQuestionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addQuestionButtonActionPerformed
        quiz.addQuestion(new Question(questionNumber, questionTextField.getText(), answerTextField.getText(), QuestionType.BASIC));
        questionNumber++;
        questionTextField.setText("");
        answerTextField.setText("");
    }//GEN-LAST:event_addQuestionButtonActionPerformed

    private void doneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneButtonActionPerformed
        quiz.setName(selectedName);
        quiz.addQuestion(new Question(questionNumber, questionTextField.getText(), answerTextField.getText(), QuestionType.BASIC));
        questionNumber++;
        questionTextField.setText("");
        answerTextField.setText("");

        dataHandler.getSubjectWithName(subjectName).addQuiz(quiz);
        subjectWindow.refreshTable();
        subjectWindow.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_doneButtonActionPerformed


    public void setSubjectWindow(SubjectWindow subjectWindow) {
        this.subjectWindow = subjectWindow;
    }
    
    public void setDataHandler(DataHandler dataHandler) {
        this.dataHandler = dataHandler;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addQuestionButton;
    private javax.swing.JLabel answerLabel;
    private javax.swing.JTextField answerTextField;
    private javax.swing.JButton doneButton;
    private javax.swing.JLabel questionLabel;
    private javax.swing.JTextField questionTextField;
    // End of variables declaration//GEN-END:variables
}
