/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 *
 * Author: Kristen Belanger
 */
package quizprogram;

public class SubjectBuilder extends BaseWindow {

    private MainWindow mainWindow;
    private Subject newSubject;
    
    /**
     * Creates new form SubjectBuilder
     */
    public SubjectBuilder(MainWindow mainWindow) {
        super();
        initComponents();
        this.mainWindow = mainWindow;
        setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        subjectNameLabel = new javax.swing.JLabel();
        subjectNameTextField = new javax.swing.JTextField();
        createSubjectButton = new javax.swing.JButton();
        typeComboBox = new javax.swing.JComboBox<>();
        typeLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        subjectNameLabel.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        subjectNameLabel.setText("Enter subject name:");

        createSubjectButton.setBackground(new java.awt.Color(51, 51, 255));
        createSubjectButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        createSubjectButton.setForeground(new java.awt.Color(255, 255, 51));
        createSubjectButton.setText("Create Subject");
        createSubjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createSubjectButtonActionPerformed(evt);
            }
        });

        typeComboBox.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        typeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BASIC", "SPELLING" }));

        typeLabel.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        typeLabel.setText("Subject Type:");
        typeLabel.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(subjectNameLabel)
                            .addComponent(typeLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subjectNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(createSubjectButton)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subjectNameLabel)
                    .addComponent(subjectNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeLabel)
                    .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(createSubjectButton)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createSubjectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createSubjectButtonActionPerformed
        // TODO add your handling code here:
        if (null != subjectNameTextField.getText() && !subjectNameTextField.getText().isEmpty()) {

            String selectedTypeStr = (String) typeComboBox.getSelectedItem();
            QuestionType selectedType = QuestionType.fromString(selectedTypeStr);
            newSubject = new Subject(subjectNameTextField.getText(), selectedType);
            subjectNameTextField.setText("");
            dataHandler.addSubject(newSubject);
            mainWindow.refreshTable();
            mainWindow.setVisible(true);
            this.setVisible(false);
        }
        
    }//GEN-LAST:event_createSubjectButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createSubjectButton;
    private javax.swing.JLabel subjectNameLabel;
    private javax.swing.JTextField subjectNameTextField;
    private javax.swing.JComboBox<String> typeComboBox;
    private javax.swing.JLabel typeLabel;
    // End of variables declaration//GEN-END:variables
}
