/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quizprogram;

import quizprogram.DataHandler;
import quizprogram.Subject;

/**
 *
 * @author dianebelanger
 */
public class SubjectBuilder extends BaseWindow {

    private MainWindow mainWindow;
    private Subject newSubject;
    
    /**
     * Creates new form SubjectBuilder
     */
    public SubjectBuilder(MainWindow mainWindow) {
        super();
        initComponents();
        this.mainWindow = mainWindow;
        setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        subjectNameLabel = new javax.swing.JLabel();
        subjectNameTextField = new javax.swing.JTextField();
        createSubjectButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        subjectNameLabel.setText("Enter subject name:");

        createSubjectButton.setText("Create Subject");
        createSubjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createSubjectButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(subjectNameLabel)
                .addGap(30, 30, 30)
                .addComponent(subjectNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(createSubjectButton)
                .addGap(52, 52, 52))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subjectNameLabel)
                    .addComponent(subjectNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(createSubjectButton)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createSubjectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createSubjectButtonActionPerformed
        // TODO add your handling code here:
        if (null != subjectNameTextField.getText() && !subjectNameTextField.getText().isEmpty()) {
            newSubject = new Subject(subjectNameTextField.getText());
            subjectNameTextField.setText("");
            dataHandler.addSubject(newSubject);
            mainWindow.refreshTable();
            mainWindow.setVisible(true);
            this.setVisible(false);
        }
        
    }//GEN-LAST:event_createSubjectButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createSubjectButton;
    private javax.swing.JLabel subjectNameLabel;
    private javax.swing.JTextField subjectNameTextField;
    // End of variables declaration//GEN-END:variables
}
